#!/bin/bash
sleep 4
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start wireplumber
/usr/lib/xdg-desktop-portal-wlr -r -l TRACE &
sleep 4
/usr/lib/xdg-desktop-portal &
